using System.Text;

namespace BanglaHost.Core;

/// <summary>
/// Renders nginx config for Windows — the analog of the mac engine's
/// <c>render_nginx_main</c> / <c>render_nginx_php_vhost</c>. Two key Windows changes:
/// (1) <c>fastcgi_pass 127.0.0.1:&lt;port&gt;</c> instead of a unix socket, and
/// (2) every path is emitted with forward slashes (nginx on Windows rejects
/// back-slashes in directives).
/// </summary>
public static class NginxConfig
{
    /// <summary>nginx wants forward slashes even on Windows.</summary>
    public static string Fwd(string p) => p.Replace('\\', '/');

    /// <summary>Bind address for listen directives: all interfaces when LAN sharing is on
    /// (so other devices on the network can reach the site), else loopback only.</summary>
    private static string Bind(Config cfg) => cfg.LanSharing ? "0.0.0.0" : "127.0.0.1";

    /// <summary>Parse the "port forwarding" setting (e.g. "8080" or "8080:80") into the external
    /// port to add an extra HTTP listen on. Returns 0 when unset/invalid/equal to the HTTP port.</summary>
    private static int ExtraListenPort(Config cfg)
    {
        var s = (cfg.PortForwarding ?? "").Trim();
        if (s.Length == 0) return 0;
        var ext = s.Split(':')[0].Trim();
        return int.TryParse(ext, out var p) && p is > 0 and < 65536 && p != cfg.HttpPort ? p : 0;
    }

    private static string Prefix => Tools.NginxPrefix() ?? Path.Combine(Paths.Bin, "nginx");
    // STABLE conf dir (Home\nginx\conf) — fastcgi_params + mime.types are copied here from the
    // versioned nginx build so site configs that include them DON'T break when nginx is updated.
    private static string StableConfDir => Path.Combine(Paths.Home, "nginx", "conf");
    private static string MimeTypes     => Fwd(Path.Combine(StableConfDir, "mime.types"));
    private static string FastcgiParams => Fwd(Path.Combine(StableConfDir, "fastcgi_params"));

    /// <summary>Copy a conf file from the (versioned) nginx build to the stable dir, and make sure the
    /// runtime dirs nginx needs exist (it opens its prefix-relative logs\error.log before the config).</summary>
    private static void PrepareRuntime()
    {
        foreach (var d in new[] { Path.Combine(Paths.Home, "logs"), Path.Combine(Paths.Home, "run"),
                                  Path.Combine(Paths.Home, "tmp"), Path.Combine(Paths.Home, "nginx", "logs"),
                                  Paths.NginxSites, StableConfDir })
            try { Directory.CreateDirectory(d); } catch { }

        foreach (var name in new[] { "fastcgi_params", "mime.types" })
            try
            {
                var src = Path.Combine(Prefix, "conf", name);
                if (File.Exists(src)) File.Copy(src, Path.Combine(StableConfDir, name), overwrite: true);
            }
            catch { }

        // Heal site configs written against a now-removed nginx version dir → repoint to the stable copy.
        try
        {
            if (Directory.Exists(Paths.NginxSites))
                foreach (var f in Directory.GetFiles(Paths.NginxSites, "*.conf"))
                {
                    var txt = File.ReadAllText(f);
                    var fixedTxt = System.Text.RegularExpressions.Regex.Replace(
                        txt, @"include\s+\S*?nginx-[\d.]+/conf/fastcgi_params\s*;",
                        $"include {FastcgiParams};");
                    if (fixedTxt != txt) File.WriteAllText(f, fixedTxt);
                }
        }
        catch { }
    }

    public static void RenderMain(Config cfg)
    {
        PrepareRuntime();
        var home = Fwd(Paths.Home);
        var conf = Path.Combine(Paths.Home, "nginx", "nginx.conf");
        var sb = new StringBuilder();
        sb.Append($$"""
        # Generated by BanglaHost (Windows) — do not edit by hand (regenerated on init / site changes).
        # No `user` directive: Windows nginx ignores it. PHP runs as php-cgi.exe over TCP.
        worker_processes auto;
        error_log {{home}}/logs/nginx-error.log;
        pid {{home}}/run/nginx.pid;
        events {
            worker_connections 4096;
        }
        http {
            include {{MimeTypes}};
            default_type application/octet-stream;
            access_log {{home}}/logs/nginx-access.log;
            client_body_temp_path {{home}}/tmp/client_body;
            proxy_temp_path       {{home}}/tmp/proxy;
            fastcgi_temp_path     {{home}}/tmp/fastcgi;
            uwsgi_temp_path       {{home}}/tmp/uwsgi;
            scgi_temp_path        {{home}}/tmp/scgi;

            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 4096;
            server_names_hash_bucket_size 128;
            server_tokens off;
            client_max_body_size 2048m;

            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_busy_buffers_size 64k;
            fastcgi_read_timeout 600;
            fastcgi_connect_timeout 60;

            gzip on;
            gzip_comp_level 5;
            gzip_min_length 256;
            gzip_proxied any;
            gzip_vary on;
            gzip_types text/plain text/css text/xml text/javascript application/json
                       application/javascript application/xml application/xml+rss
                       application/rss+xml image/svg+xml application/wasm font/ttf font/otf;

            # Default server: serve the BanglaHost dashboard at http://localhost (and for any
            # unmatched host) instead of a dead `return 444` — so visiting localhost first (the way
            # XAMPP/Laragon users do) shows a real page listing every site, not an empty reply.
            # Individual sites still match by their own server_name; nothing leaks the "first site".
            server {
                listen {{Bind(cfg)}}:{{cfg.HttpPort}} default_server;
                server_name localhost;
                root {{home}}/dashboard;
                index index.html;
                access_log {{home}}/logs/dashboard-access.log;
                location / { try_files $uri $uri/ =404; }
            }

            include {{home}}/nginx/sites/*.conf;
        }

        """);
        Directory.CreateDirectory(Path.GetDirectoryName(conf)!);
        File.WriteAllText(conf, sb.ToString());
        RenderDashboard(cfg);
    }

    /// <summary>Render the static landing page served at http://localhost — a branded index that
    /// lists every BanglaHost site with a clickable link, so localhost is a useful home page rather
    /// than a dead end. Regenerated on every RenderMain (i.e. whenever sites change).</summary>
    private static void RenderDashboard(Config cfg)
    {
        var dir = Path.Combine(Paths.Home, "dashboard");
        try { Directory.CreateDirectory(dir); } catch { }

        // Collect sites from the rendered vhosts: server_name + scheme (https if it listens ssl).
        var sites = new List<(string domain, bool https)>();
        try
        {
            if (Directory.Exists(Paths.NginxSites))
                foreach (var f in Directory.GetFiles(Paths.NginxSites, "*.conf"))
                {
                    var txt = File.ReadAllText(f);
                    var m = System.Text.RegularExpressions.Regex.Match(txt, @"server_name\s+([^;]+);");
                    if (!m.Success) continue;
                    var domain = m.Groups[1].Value.Trim().Split(' ')[0];
                    if (domain.Length == 0 || domain == "_") continue;
                    var https = System.Text.RegularExpressions.Regex.IsMatch(txt, @"listen[^;]*\sssl");
                    sites.Add((domain, https));
                }
        }
        catch { /* a malformed vhost must never break dashboard rendering */ }
        sites.Sort((a, b) => string.CompareOrdinal(a.domain, b.domain));

        string Esc(string s) => System.Net.WebUtility.HtmlEncode(s);
        var rows = new StringBuilder();
        if (sites.Count == 0)
            rows.Append("<p class='empty'>No sites yet — add one from the BanglaHost app, then refresh this page.</p>");
        else
        {
            rows.Append("<ul class='sites'>");
            foreach (var (domain, https) in sites)
            {
                var url = $"{(https ? "https" : "http")}://{domain}";
                rows.Append($"<li><a href='{Esc(url)}'><span class='dot {(https ? "s" : "")}'></span>{Esc(domain)}<span class='scheme'>{(https ? "https" : "http")}</span></a></li>");
            }
            rows.Append("</ul>");
        }

        var html = $$"""
        <!doctype html>
        <html lang='en'>
        <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <title>BanglaHost</title>
        <style>
          :root { color-scheme: light dark; }
          * { box-sizing: border-box; }
          body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; padding:24px;
                 font-family:-apple-system,'Segoe UI',Roboto,Arial,sans-serif; background:#0f172a; color:#e2e8f0; }
          .card { width:100%; max-width:640px; background:#111827; border:1px solid #1f2937; border-radius:18px;
                  overflow:hidden; box-shadow:0 20px 60px rgba(0,0,0,.45); }
          .hero { background:linear-gradient(135deg,#2563eb,#7c3aed); padding:34px 32px; }
          .badge { display:inline-block; font-size:12px; letter-spacing:.08em; text-transform:uppercase;
                   background:rgba(255,255,255,.18); padding:4px 11px; border-radius:999px; }
          h1 { margin:14px 0 4px; font-size:28px; line-height:1.15; }
          .hero p { margin:0; opacity:.92; }
          .body { padding:22px 28px 28px; }
          .sites { list-style:none; margin:0; padding:0; }
          .sites li { margin:0 0 9px; }
          .sites a { display:flex; align-items:center; gap:12px; padding:13px 16px; border-radius:12px;
                     background:#0b1220; border:1px solid #1f2937; text-decoration:none; color:#e2e8f0;
                     font-family:ui-monospace,'Cascadia Code',Consolas,monospace; font-size:15px; }
          .sites a:hover { border-color:#3b82f6; background:#0d1628; }
          .dot { width:9px; height:9px; border-radius:50%; background:#64748b; flex:0 0 auto; }
          .dot.s { background:#22c55e; }
          .scheme { margin-left:auto; font-size:12px; color:#94a3b8; }
          .empty { color:#94a3b8; font-size:14px; }
          .foot { margin-top:18px; display:flex; justify-content:space-between; align-items:center;
                  font-size:13px; color:#94a3b8; }
          .foot strong { color:#cbd5e1; }
        </style>
        </head>
        <body>
          <div class='card'>
            <div class='hero'>
              <span class='badge'>Running</span>
              <h1>BanglaHost</h1>
              <p>Your local web server is up. Pick a site below.</p>
            </div>
            <div class='body'>
              {{rows}}
              <div class='foot'>
                <span>Powered by <strong>BanglaHost</strong></span>
                <span>Mohammad Sheikh Shahinur Rahman</span>
              </div>
            </div>
          </div>
        </body>
        </html>
        """;
        try { File.WriteAllText(Path.Combine(dir, "index.html"), html); } catch { }
    }

    /// <summary>Emit the listen/ssl lines for a domain (HTTP always; HTTPS if a cert exists).</summary>
    private static string ListenBlock(string domain, Config cfg)
    {
        var cert = Path.Combine(Paths.Certs, $"{domain}.pem");
        var key  = Path.Combine(Paths.Certs, $"{domain}-key.pem");
        var bind = Bind(cfg);
        var sb = new StringBuilder();
        sb.AppendLine($"    listen {bind}:{cfg.HttpPort};");
        var extra = ExtraListenPort(cfg);
        if (extra != 0) sb.AppendLine($"    listen {bind}:{extra};   # port forwarding");
        if (File.Exists(cert) && File.Exists(key))
        {
            // QUIC/HTTP-3 isn't available in the bundled Windows nginx, so "QUIC enabled" applies
            // HTTP/2 over TLS (the listen-parameter form works across nginx versions).
            sb.AppendLine($"    listen {bind}:{cfg.HttpsPort} ssl{(cfg.QuicEnabled ? " http2" : "")};");
            sb.AppendLine($"    ssl_certificate {Fwd(cert)};");
            sb.AppendLine($"    ssl_certificate_key {Fwd(key)};");
        }
        else
        {
            sb.AppendLine($"    # HTTPS not provisioned — run: banglahost secure {domain}");
        }
        return sb.ToString().TrimEnd('\r', '\n');
    }

    /// <summary>nginx serves PHP directly via php-cgi over TCP (render_nginx_php_vhost analog).</summary>
    public static void RenderPhpVhost(string name, string domain, string root, string phpKey, Config cfg)
    {
        var version = Services.PhpVersion(phpKey, cfg);
        var port = PhpCgi.PortFor(version);
        var home = Fwd(Paths.Home);
        var conf = Path.Combine(Paths.NginxSites, $"{name}.conf");
        var body = $$"""
        # BanglaHost site: {{name}}  ({{domain}})  php={{phpKey}} server=nginx
        server {
        {{ListenBlock(domain, cfg)}}
            server_name {{domain}};
            root {{Fwd(root)}};
            index index.php index.html index.htm;

            access_log {{home}}/logs/{{name}}-access.log;
            error_log  {{home}}/logs/{{name}}-error.log;

            location / { try_files $uri $uri/ /index.php?$query_string; }

            location ~ \.php$ {
                try_files $uri =404;
                include {{FastcgiParams}};
                fastcgi_pass 127.0.0.1:{{port}};
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
            }

            location ~ /\.(?!well-known).* { deny all; }
        }

        """;
        Directory.CreateDirectory(Paths.NginxSites);
        File.WriteAllText(conf, body);
    }

    /// <summary>nginx fronts (TLS/80/443) and proxies the whole host to the Apache backend.</summary>
    public static void RenderApacheFront(string name, string domain, string root, string phpKey, int apachePort, Config cfg)
    {
        var home = Fwd(Paths.Home);
        var conf = Path.Combine(Paths.NginxSites, $"{name}.conf");
        var body = $$"""
        # BanglaHost site: {{name}}  ({{domain}})  php={{phpKey}} server=apache
        server {
        {{ListenBlock(domain, cfg)}}
            server_name {{domain}};
            root {{Fwd(root)}};   # served by Apache (:{{apachePort}}); kept for tooling

            access_log {{home}}/logs/{{name}}-access.log;
            error_log  {{home}}/logs/{{name}}-error.log;

            location / {
                proxy_pass http://127.0.0.1:{{apachePort}};
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 600;
            }
        }

        """;
        Directory.CreateDirectory(Paths.NginxSites);
        File.WriteAllText(conf, body);
    }

    /// <summary>Front a local HTTP service (e.g. Mailpit :8025) at a *.tld host (render_nginx_proxy_site analog).</summary>
    public static void RenderProxyVhost(string name, string domain, int port, Config cfg)
    {
        var conf = Path.Combine(Paths.NginxSites, $"{name}.conf");
        var body = $$"""
        # BanglaHost site: {{name}}  ({{domain}})  php=- server=proxy -> 127.0.0.1:{{port}}
        server {
        {{ListenBlock(domain, cfg)}}
            server_name {{domain}};
            location / {
                proxy_pass http://127.0.0.1:{{port}};
                proxy_set_header Host $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 600;
            }
        }

        """;
        Directory.CreateDirectory(Paths.NginxSites);
        File.WriteAllText(conf, body);
    }
}
